### ISSUE TITLE
Implement registration at Instance Registry in the Components

### ISSUE THREAD

**Issue by johannesduesing** [delphi-hub/delphi#11]
In order to show all running components in the management application, the components themselves need to register at the Instance Registry. This should be done on startup, but is not mandatory, as components should be able to boot without the Instance Registry being deployed. 
We also have to think of a way of passing / storing the IP address of the Instance Registry to the individual components.

- [ ] Make crawler register at instance registry
- [ ] Make WebAPI register at instance registry
- [x] Make WebApp register at instance registry

**Comment by sami-cseseu** [comment]
I want to work in WebAPP part as I worked on it previously. I can make a get request is the component is already there in the database? then i can change the status. I will create a new instance entry otherwise. Component will enter an entry to the instance registry will there will be a default ip for each component? will there be a default instance registry address as well? anybody?
